### ISSUE TITLE
rbison Timeout-URLs May have changed

### ISSUE THREAD

**Issue by RedWinter16** [ropensci/rbison#45]
Hi,

When I try to run rbison I receive the following error:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

My proxy settings are in place and I am able to communicate with the gbif API through rgbif without issue.

**Comment by RedWinter16** [comment]
Issue solved. The fault is with the 'httr' package config settings. These must have changed when I updated R. If anyone else runs into this issue:

library(httr)
set_config(use_proxy(url = "enteryourproxyhere_", port = "enterporthere"))

**Comment by sckott** [comment]
@RedWinter16 thanks for the report, and the fix. do you know what versions of `httr` you had before and after updating?

**Comment by RedWinter16** [comment]
Unfortunately I do not know what version of httr I was running before updating my installed packages.

**Comment by sckott** [comment]
okay, thanks anyway
