### ISSUE TITLE
How do you extract "eventDate" column from the database with bison()?

### ISSUE THREAD

**Issue by kpmainali** [ropensci/rbison#65]
Example code:

```r
download <- bison(species = "Strix occidentalis caurina", type = "scientific_name",
   count = 10000000)
bison.pts <- download$points
head(bison.pts)
```

**Comment by sckott** [comment]
try `bison_solr` intead. `bison` doesn't return date data

```r
z <- bison_solr(scientificName = "Strix occidentalis caurina", rows = 10)
#> z$points$eventDate
#>  [1] "2017-05-17" "2014-06-15" "2014-06-15" "1996-01-01" "1996-01-01" "1992-01-01" "2000-01-01" "1980-11-05"
#>  [9] "2003-01-01" "1991-07-16"
```

**Comment by kpmainali** [comment]
bison_solr() does not allow me to download more than 10k points. Is there a way to not be limited by the number of points and be able to get the date of records?

**Comment by sckott** [comment]
try using the `rows` and `start` parameters. e.g,. 

```r
# records from 1 to 10
bison_solr(scientificName = "Strix occidentalis caurina", rows = 10)
# records from 10 to 20
bison_solr(scientificName = "Strix occidentalis caurina", rows = 10, start = 10)
```

important if you get to big numbers like 10000 to write them like `10000L` to make sure they don't get turned into scientific notation which will not work when sent to USGS web service
