### ISSUE TITLE
Update on BISON

### ISSUE THREAD

**Issue by albenson-usgs** [ropensci/rbison#69]
We are moving away from the 10-year-old infrastructure of the existing BISON website https://bison.usgs.gov/ to a GBIF data portal for the U.S. [www.gbif.us] provided by the Global Biodiversity Information Facility (GBIF), which will be live on October 1, 2021.

This move will help us better align our processes and data delivery mechanisms with those of GBIF and provide more timely access to new species occurrence data being added for the U.S. and U.S. Territories into GBIF.

The existing BISON website will be taken down on December 17, 2021 at which time users will be redirected to www.gbif.us.

Alternatives to our existing BISON APIs are under development. In the meantime, we suggest users interact with the GBIF APIs, described at https://www.gbif.org/developer/summary

You can access species occurrence data for the United States and U.S. Territories via the new pilot implementation of the GBIF data portal for the U.S. at www.gbif.us on October 1, 2021.

**Comment by sckott** [comment]
Thanks @albenson-usgs ! 

rgbif users can take advantage of rgbif https://github.com/ropensci/rgbif or https://github.com/gbif/pygbif if you use Python - Both are maintained now by the GBIF team
