### ISSUE TITLE
Error for rbison on the docs server

### ISSUE THREAD

**Issue by maelle** [ropensci/rbison#70]
https://github.com/r-universe/ropensci/runs/4694614258?check_suite_focus=true

```
-- Building articles -----------------------------------------------------------
Writing 'articles/index.html'
Reading 'vignettes/other_functions.Rmd'
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 53-54 (other_functions.Rmd) 
Error : Internal Server Error (HTTP 500)
```

**Comment by sckott** [comment]
Thanks @maelle - yeah see #69 - i think the thing to do is archive this repo. I'd archive it on cran but they won't let me archive cran pkgs anymore

**Comment by maelle** [comment]
No comment on the impossibility to perform archivals :sweat_smile: But much sympathy!
